language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux
matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=2.7.14
  - os: osx
    language: generic
    env: PYTHON=3.4.8
  - os: osx
    language: generic
    env: PYTHON=3.5.5
  - os: osx
    language: generic
    env: PYTHON=3.6.4
before_install:
  - pip install configobj
  - pip install pytest-cov
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update
      brew install openssl readline
      brew outdated pyenv || brew upgrade pyenv
      brew install pyenv-virtualenv
      pyenv install $PYTHON
      export PYENV_VERSION=$PYTHON
      export PATH="/Users/travis/.pyenv/shims:${PATH}"
      pyenv-virtualenv venv
      source venv/bin/activate
      python --version
    fi
# command to install code
install:
  - python setup.py install --api-key=$ILL_KEY
# command to run tests
script:
  - python setup.py pytest
after_success:
  - coveralls
