language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux
  - osx
before_install:
  - pip install configobj
# command to install code
install:
  - python setup.py install --api-key=$ILL_KEY
# command to run tests
script:
  - pytest --cov --doctest-module
after_success:
  - coveralls
