language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux
  - osx
# command to install dependencies
install:
  - python setup.py install --api-key=$ILL_KEY
# command to run tests
script:
  - coverage run -m mond_project.data_utils.data_read_utils
after_success:
  - coveralls
